import { Config } from "@stencil/core";
import { reactOutputTarget as react } from "@stencil/react-output-target";
import { sass } from "@stencil/sass";

export const config: Config = {
  globalStyle: "src/global/app.css",
  globalScript: "src/global/app.ts",
  plugins: [sass()],
  namespace: "stencil-carousel",
  outputTargets: [
    react({
      // name of the Stencil Component Library
      componentCorePackage: "stencil-carousel",
      // This file gets generated by React wrapper function and contains definitions of all Wrapper components
      proxiesFile:
        "../component-library-react/src/components/stencil-generated/index.ts",
      includeDefineCustomElements: true,
    }),
    {
      type: "dist",
      esmLoaderPath: "../loader",
    },
    {
      type: "dist-custom-elements",
    },
    {
      type: "docs-readme",
    },
    {
      type: "www",
      serviceWorker: null, // disable service workers
    },
  ],
};
