/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface StencilCarousel {
        "pause": boolean;
        "showStatus": boolean;
        "timeout": number;
    }
}
export interface StencilCarouselCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLStencilCarouselElement;
}
declare global {
    interface HTMLStencilCarouselElement extends Components.StencilCarousel, HTMLStencilElement {
    }
    var HTMLStencilCarouselElement: {
        prototype: HTMLStencilCarouselElement;
        new (): HTMLStencilCarouselElement;
    };
    interface HTMLElementTagNameMap {
        "stencil-carousel": HTMLStencilCarouselElement;
    }
}
declare namespace LocalJSX {
    interface StencilCarousel {
        "onClickEvent"?: (event: StencilCarouselCustomEvent<MouseEvent>) => void;
        "pause"?: boolean;
        "showStatus"?: boolean;
        "timeout"?: number;
    }
    interface IntrinsicElements {
        "stencil-carousel": StencilCarousel;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "stencil-carousel": LocalJSX.StencilCarousel & JSXBase.HTMLAttributes<HTMLStencilCarouselElement>;
        }
    }
}
